// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "def03c6c-18a6-468b-b92c-4ac99b83c687";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDisplayModeChange();

float humidity;
float temp_c;
float temp_f;
int display_mode;
int water_level;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp_c, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp_f, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(display_mode, READWRITE, ON_CHANGE, onDisplayModeChange);
  ArduinoCloud.addProperty(water_level, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
